# Generated by Django 4.2.29 on 2026-04-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leadactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='external_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
